services:

  postgres:
    image: postgres:12.2-alpine
    container_name: postgres_auth_mapps_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${AUTH_DATABASE_USER}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
      POSTGRES_DB: ${AUTH_DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_mapps_auth_data:/var/lib/postgresql/data

  migrator:
    image: ${DOCKER_LOGIN}/mappsauth-migrator:latest
    container_name: mapps-auth-migrator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: "user=${AUTH_DATABASE_USER} password=${AUTH_DATABASE_PASSWORD} host=postgres dbname=${AUTH_DATABASE_NAME} sslmode=disable"
    command: goose up -dir ./migrations

  app:
    image: ${DOCKER_LOGIN}/mappsauth:latest
    container_name: mapps-auth
    depends_on:
      migrator:
        condition: service_completed_successfully
    env_file:
      - ./mapps_auth.env
    ports:
      - ${EXTERNAL_PORT}:${APP_CONTAINER_PORT}

volumes:
  postgres_mapps_auth_data:
