name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Docker login
        run: echo ${{ secrets.DOCKER_AT }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

      - name: Create .env file
        run: echo "${{secrets.ENV}}" > $HOME/.env

      - name: cp .env file into mapps_auth.env
        run: cp $HOME/.env $HOME/mapps_auth.env

      - name: Download docker-compose.yml
        run: curl -o ${HOME}/docker-compose.yml https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/main/docker-compose.yaml

      - name: Drop oldest container
        run: docker compose -f $HOME/docker-compose.yml down

      - name: fetch new image
        run : docker compose -f $HOME/docker-compose.yml pull

      - name: up postrges container
        run: docker compose -f $HOME/docker-compose.yml up -d postgres

      - name: up migrator container
        run: docker compose -f $HOME/docker-compose.yml up migrator

      - name: up app container
        run: docker compose -f $HOME/docker-compose.yml up -d app
